name: GlobalAuth
main: Cybertech\Main
version: 1.0.0.1
api: 1.0.0.1 

commands:
    login:
        description: "Base Bounty Command"
        permission: skill
        useage: "/test"
    
permissions:
    skill:
        default: true
        description: "Only skill Permission"